/***************************************************************************
   Copyright (C) 2016 by Tapio Mattila

   This program is distributed under BSD license
  (http://www.opensource.org/licenses/mit-license.html)
 ***************************************************************************/
#ifndef CNUMBERGENERATORH
#define CNUMBERGENERATORH

#include <string>
#include "settings.h"
using namespace std;

/**
 * Number generator class.
 *
 * This class is responsible of calculating the numbers used
 * in game questions. Numbers are generated by standard random
 * number generator (srand) and the results of certain calculation
 * is also saved at the same time.
 *
 * Note that fractional numbers are not supported by this class.
 * 
 * \version 1.0 06.01.2006 / mtm
 */
class cNumberGenerator
{
	int m_x;
	int m_y;
	
	int m_maxX;
	int m_maxY;
	
	void initialize();

public:
	cNumberGenerator();
	~cNumberGenerator();
	
	inline int x()				{return m_x;}
	inline int y()				{return m_y;}
	
	void generateFrom(cSettings* settings);
	int generate(int max);
	
	int intValue(cSettings* settings);
	string strValue(cSettings* settings);
	string strDivide();
	string strAdd();
	string strSubtract();
};

#endif
